sudo: false
dist: trusty
language: ruby
cache: bundler
install:
  - gem install bundler -v 1.17.3
  - bundle _1.17.3_ install --jobs=3 --retry=3

branches:
  only:
    - master

rvm:
  - 2.1
  - 2.2
  - 2.3.0
  - 2.3.3

script: bundle exec rspec
before_script:
  - bundle exec rake app:db:create
  - bundle exec rake app:db:migrate
  - bundle exec rake app:db:test:prepare
