sudo: false
dist: trusty
language: ruby
cache: bundler

branches:
  only:
    - master

rvm:
  - 2.3.0

before_script:
  - bundle exec rake app:db:create
  - bundle exec rake app:db:migrate
  - bundle exec rake app:db:test:prepare

script: bundle exec rspec
